// Message Broker Auth
export const QUEUE_AUTH_PERMISSION_ROLE = 'QUEUE_AUTH_PERMISSION_ROLE';
export const QUEUE_AUTH_ISADMIN = 'QUEUE_AUTH_ISADMIN';
export const QUEUE_AUTH_GENERATE_TOKEN_JWT = 'QUEUE_AUTH_GENERATE_TOKEN_JWT';
export const QUEUE_AUTH_READ_TOKEN_JWT = 'QUEUE_AUTH_READ_TOKEN_JWT';

