// Message Broker User
export const QUEUE_USER_CREATE = 'QUEUE_USER_CREATE';
export const QUEUE_USER_UPDATE = 'QUEUE_USER_UPDATE';
export const QUEUE_USER_DELETE = 'QUEUE_USER_DELETE';
export const QUEUE_USER_LOGIN = 'QUEUE_USER_LOGIN';
export const QUEUE_USER_GET = 'QUEUE_USER_GET';
export const QUEUE_USER_GET_ALL = 'QUEUE_USER_GET_ALL';

export const QUEUE_USER_SIGNUP_PROVIDER = 'QUEUE_USER_SIGNUP_PROVIDER';

export const QUEUE_USER_VERIFY_EMAIL = 'QUEUE_USER_VERIFY_EMAIL';
export const QUEUE_USER_FORGET_PASSWORD = 'QUEUE_USER_FORGET_PASSWORD';
export const QUEUE_USER_RESET_PASSWORD = 'QUEUE_USER_RESET_PASSWORD';
export const QUEUE_USER_CHANGE_PASSWORD = 'QUEUE_USER_CHANGE_PASSWORD';
