FROM node:16-alpine

RUN mkdir -p /app && chown -R node:node /app

ENV PATH /app/node_modules/.bin:$PATH

WORKDIR /app

COPY . .
RUN find index.* -maxdepth 0 -name 'index.gateway.js' -prune -o -exec rm -rf '{}' ';'
RUN rm -rf services

RUN yarn install

EXPOSE 5000

RUN yarn test test/healthcheck.gateway.test.js

CMD ["node", "index.gateway.js"]

# docker build -t gateway_service:latest -f Dockerfile.gateway .
# docker run -p 5000:5000 gateway_service