version: "3.8"

services:

   local-development:
      container_name: local-development
      environment:
         - NODE_ENV=development
         - TZ=Asia/Jakarta
         - CHOKIDAR_USEPOLLING=true
         - WATCHPACK_POLLING=true
      build:
         dockerfile: Dockerfile.mono
         context: .
      restart: always
      command: yarn dev
      ports:
         - 5000:5000
      volumes:
         - ./source:/app
         - /app/node_modules
      networks:
         - bridge
    
networks:
  bridge:
    driver: bridge