version: "3.8"

services:

   rabbitmq:
      image: rabbitmq:3.8-management-alpine
      container_name: rabbitmq
      restart: always
      env_file:
         - ./.env
      environment:
         - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
         - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
      ports:
         - 15672:15672
         - 5672:5672
      networks:
         - bridge

   mongodb:
      container_name: mongodb
      image: mongo:latest
      restart: always
      env_file:
         - ./.env
      environment:
         - TZ=${TZ}
         - MONGO_INITDB_DATABASE=admin
         - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USER}
         - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASS}
      ports:
         - 27017:27017
      volumes:
         - ./data/db:/data/db
      networks:
         - bridge

   mongodb-cron-backup:
      image: randyproxz/mongodb-cron-backup
      container_name: mongodb-cron-backup
      depends_on:
         - mongodb
      restart: always
      volumes:
         - ./data/backup:/backup
      env_file:
         - ./.env
      environment:
         - TZ=${TZ}
         - MONGO_HOST=${MONGODB_HOST}
         - MONGO_PORT=${MONGODB_PORT}
         - MONGO_USER=${MONGODB_USER}
         - MONGO_DB=${MONGODB_DB}
         - MONGO_PASS=${MONGODB_PASS}
         - CRON_TIME=${MONGODB_CRON_BACKUP_TIME}
         - INIT_BACKUP=${MONGODB_INIT_BACKUP}
         - MAX_BACKUPS=${MONGODB_MAX_BACKUPS}
      networks:
         - bridge

networks:
  bridge:
    driver: bridge