version: "3.8"

services:
   local-development:
      container_name: local-development
      build:
         dockerfile: Dockerfile.local
         context: .
      restart: "always"
      ports:
         - "5000:5000"
      volumes:
         - ./source:/app
         - /app/node_modules
      networks:
         - local-bridge
    
networks:
  local-bridge:
    driver: bridge

# docker-compose -f docker-compose.local.yml up