version: "3.8"

services:

   rabbitmq:
      image: rabbitmq:3.8-management-alpine
      container_name: rabbitmq
      environment:
         - RABBITMQ_DEFAULT_USER=adminmq
         - RABBITMQ_DEFAULT_PASS=123qwe
      ports:
         - 15672:15672
         - 5672:5672
      networks:
         - local-bridge

   mongodb:
      container_name: mongodb
      image: mongo:latest
      environment:
         - MONGO_INITDB_DATABASE=admin
         - MONGO_INITDB_ROOT_USERNAME=admindb
         - MONGO_INITDB_ROOT_PASSWORD=123qwe
      ports:
         - 27017:27017
      volumes:
         - ./data/db:/data/db
      networks:
         - local-bridge

networks:
  local-bridge:
    driver: bridge

# docker-compose up -d