version: "3.8"

services:

  local_development:
    container_name: local_development
    build:
      dockerfile: Dockerfile
      context: .
    restart: "always"
    command: 'yarn dev'
    ports:
      - "5000:5000"
    volumes:
      - ./:/app
      - /app/node_modules

# docker-compose -f docker-compose.local.yml up -d