version: "3.8"

services:
      
  auth_service:
    image: "auth_service"
    restart: "always"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.auth.rule=Host(`auth.domain.com`)"
      - "traefik.http.routers.auth.entrypoints=web"
      - "traefik.http.routers.auth.entrypoints=websecure"
      - "traefik.http.routers.auth.tls=true"
      - "traefik.http.routers.auth.tls.certresolver=letsencrypt"
    networks:
      - "traefik-network"

networks:
  traefik-network:
    external: true