module.exports = Object.freeze({
   ADMIN: 'admin',
   USER: 'user',

   // Message Broker Auth
   AUTH_LOGIN_MQ: 'AUTH_LOGIN_MQ',
   AUTH_PERMISSION_ACCESS_MQ: 'AUTH_PERMISSION_ACCESS_MQ',
   AUTH_PERMISSION_ROLE_MQ: 'AUTH_PERMISSION_ROLE_MQ',
   AUTH_ISADMIN_MQ: 'AUTH_ISADMIN_MQ',
   AUTH_GENERATE_TOKEN_MQ: 'AUTH_GENERATE_TOKEN_MQ',

   // Message Broker User
   USER_CREATE_MQ: 'USER_CREATE_MQ',
   USER_UPDATE_MQ: 'USER_UPDATE_MQ',
});