version: "3.8"

services:

   rabbitmq:
      image: rabbitmq:3.8-management-alpine
      container_name: 'rabbitmq'
      ports:
         - 15672:15672
         - 5672:5672

networks:
   default:
      driver: bridge

# docker-compose up -d